// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // --- ENTIDADES DEL LMS ---

            modelBuilder.Entity("Data.Entities.Categoria", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Descripcion").HasColumnType("nvarchar(max)");
                    b.Property<short>("EntityStatus").HasColumnType("smallint");
                    b.Property<string>("Nombre").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Slug").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Data.Entities.Curso", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int?>("CategoriaId").HasColumnType("int");
                    b.Property<int?>("DocenteId").HasColumnType("int");
                    b.Property<string>("Titulo").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<string>("Descripcion").HasColumnType("nvarchar(max)");
                    b.Property<string>("ImagenUrl").HasColumnType("nvarchar(max)");
                    b.Property<string>("Nivel").HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<int>("DuracionTotalMin").HasColumnType("int");
                    b.Property<int?>("MaxEstudiantes").HasColumnType("int");
                    b.Property<bool>("Publicado").HasColumnType("bit");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<DateTime?>("DeletedAt").HasColumnType("datetime2");
                    b.Property<short>("EntityStatus").HasColumnType("smallint");
                    b.HasKey("Id");
                    b.HasIndex("CategoriaId");
                    b.HasIndex("DocenteId");
                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Data.Entities.Docente", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("UsuarioId").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<string>("Biografia").HasColumnType("nvarchar(max)");
                    b.Property<string>("Especialidad").HasColumnType("nvarchar(max)");
                    b.Property<int>("TotalCursos").HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<short>("EntityStatus").HasColumnType("smallint");
                    b.HasKey("Id");
                    b.HasIndex("UsuarioId");
                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("Data.Entities.Modulo", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int?>("CursoId").HasColumnType("int");
                    b.Property<string>("Titulo").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<string>("Descripcion").HasColumnType("nvarchar(max)");
                    b.Property<int>("Orden").HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<DateTime?>("DeletedAt").HasColumnType("datetime2");
                    b.Property<short>("EntityStatus").HasColumnType("smallint");
                    b.HasKey("Id");
                    b.HasIndex("CursoId");
                    b.ToTable("Modulos");
                });

            // --- ENTIDADES DE IDENTIDAD Y SEGURIDAD ---

            modelBuilder.Entity("Data.Entities.Person", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("FirstName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("LastName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("MotherLastName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("NationalId").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("NationalIdExpedition").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateOnly>("DateOfBirth").HasColumnType("date");
                    b.Property<int>("Gender").HasColumnType("int");
                    b.Property<string>("PhoneNumber").HasColumnType("nvarchar(max)");
                    b.Property<string>("Address").HasColumnType("nvarchar(max)");
                    b.Property<string>("ProfilePictureUrl").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("People");
                });

            modelBuilder.Entity("Data.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Token").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("datetime2");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<bool>("IsRevoked").HasColumnType("bit");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Data.Entities.User", b =>
                {
                    b.Property<string>("Id").HasColumnType("nvarchar(450)");
                    b.Property<int>("PersonId").HasColumnType("int");
                    b.Property<string>("UserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("Email").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<bool>("EmailConfirmed").HasColumnType("bit");
                    b.Property<string>("PasswordHash").HasColumnType("nvarchar(max)");
                    b.Property<string>("SecurityStamp").HasColumnType("nvarchar(max)");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
                    b.Property<string>("PhoneNumber").HasColumnType("nvarchar(max)");
                    b.Property<bool>("PhoneNumberConfirmed").HasColumnType("bit");
                    b.Property<bool>("TwoFactorEnabled").HasColumnType("bit");
                    b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("datetimeoffset");
                    b.Property<bool>("LockoutEnabled").HasColumnType("bit");
                    b.Property<int>("AccessFailedCount").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                    b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex").HasFilter("[NormalizedUserName] IS NOT NULL");
                    b.HasIndex("PersonId");
                    b.ToTable("AspNetUsers", (string)null);
                });

            // --- TABLAS ESTÁNDAR DE IDENTITY ---

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id").HasColumnType("nvarchar(450)");
                    b.Property<string>("Name").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex").HasFilter("[NormalizedName] IS NOT NULL");
                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("RoleId").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
                    b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
                    b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
                    b.Property<string>("ProviderKey").HasColumnType("nvarchar(450)");
                    b.Property<string>("ProviderDisplayName").HasColumnType("nvarchar(max)");
                    b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                    b.HasKey("LoginProvider", "ProviderKey");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId").HasColumnType("nvarchar(450)");
                    b.Property<string>("RoleId").HasColumnType("nvarchar(450)");
                    b.HasKey("UserId", "RoleId");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId").HasColumnType("nvarchar(450)");
                    b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
                    b.Property<string>("Name").HasColumnType("nvarchar(450)");
                    b.Property<string>("Value").HasColumnType("nvarchar(max)");
                    b.HasKey("UserId", "LoginProvider", "Name");
                    b.ToTable("AspNetUserTokens", (string)null);
                });

            // --- DEFINICIÓN DE RELACIONES (FOREIGN KEYS) ---

            modelBuilder.Entity("Data.Entities.Curso", b =>
                {
                    b.HasOne("Data.Entities.Categoria", "Categoria").WithMany("Cursos").HasForeignKey("CategoriaId");
                    b.HasOne("Data.Entities.Docente", "Docente").WithMany("Cursos").HasForeignKey("DocenteId");
                    b.Navigation("Categoria");
                    b.Navigation("Docente");
                });

            modelBuilder.Entity("Data.Entities.Docente", b =>
                {
                    b.HasOne("Data.Entities.User", "User").WithMany().HasForeignKey("UsuarioId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.Modulo", b =>
                {
                    b.HasOne("Data.Entities.Curso", "Curso").WithMany("Modulos").HasForeignKey("CursoId");
                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("Data.Entities.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.User", b =>
                {
                    b.HasOne("Data.Entities.Person", "Person").WithMany("Users").HasForeignKey("PersonId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Person");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Data.Entities.User", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Data.Entities.User", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("Data.Entities.User", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Data.Entities.User", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            // --- NAVEGACIONES DE COLECCIÓN ---

            modelBuilder.Entity("Data.Entities.Categoria", b => { b.Navigation("Cursos"); });
            modelBuilder.Entity("Data.Entities.Curso", b => { b.Navigation("Modulos"); });
            modelBuilder.Entity("Data.Entities.Docente", b => { b.Navigation("Cursos"); });
            modelBuilder.Entity("Data.Entities.Person", b => { b.Navigation("Users"); });

#pragma warning restore 612, 618
        }
    }
}